// The iconMap object is a map of icon names to their respective Heroicons.
// This is used to render the correct icon based on the icon name.
import {
  HomeIcon,
  AcademicCapIcon,
  BriefcaseIcon,
  BoltIcon,
  BookOpenIcon,
  BuildingOfficeIcon,
  CakeIcon,
  GiftIcon,
  HeartIcon,
  LightBulbIcon,
  MusicalNoteIcon,
  PencilSquareIcon,
  RocketLaunchIcon,
  ShoppingBagIcon,
  StarIcon,
  EnvelopeIcon,
  GlobeAltIcon,
  MegaphoneIcon,
  PhotoIcon,
  UserIcon,
  PhoneIcon,
  InboxIcon,
  FireIcon,
  FilmIcon,
  FlagIcon,
} from "@heroicons/react/20/solid";

const iconMap = {
  home: HomeIcon,
  academicCap: AcademicCapIcon,
  briefcase: BriefcaseIcon,
  bolt: BoltIcon,
  bookOpen: BookOpenIcon,
  buildingOffice: BuildingOfficeIcon,
  cake: CakeIcon,
  gift: GiftIcon,
  heart: HeartIcon,
  lightBulb: LightBulbIcon,
  musicalNote: MusicalNoteIcon,
  pencilSquare: PencilSquareIcon,
  rocketLaunch: RocketLaunchIcon,
  shoppingBag: ShoppingBagIcon,
  star: StarIcon,
  envelope: EnvelopeIcon,
  globeAlt: GlobeAltIcon,
  megaphone: MegaphoneIcon,
  photo: PhotoIcon,
  user: UserIcon,
  phone: PhoneIcon,
  inbox: InboxIcon,
  fire: FireIcon,
  film: FilmIcon,
  flag: FlagIcon,
};
export default iconMap;
